### ISSUE TITLE
Error installing the application

### ISSUE THREAD

**Issue by fleza** [Hughes-Genome-Group/mlv#4]
Hi, I am following the installation and configurations steps from https://lanceotron.readthedocs.io/en/latest/mlv_developer/developer.html, but when I run 

flask find_or_create_user --firstname John --last_name Doe --email guest@somewhere.com
I got this error:

`* Serving Flask app "/mlv/app/commands/cli_commands.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "app.commands.cli_commands", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/mlv/app/commands/cli_commands.py", line 8, in <module>
    from app.jobs.jobs import get_job
  File "/mlv/app/jobs/jobs.py", line 5, in <module>
    from app.zegami.zegamiupload import update_collection,delete_collection
  File "/mlv/app/zegami/zegamiupload.py", line 9, in <module>
    from app.zegami.lib import (
ModuleNotFoundError: No module named 'app.zegami.lib'

root@cf6ebb94b997:/# flask find_or_create_user --firstname John --last_name Doe --email guest@somewhere.com
Usage: flask [OPTIONS] COMMAND [ARGS]...

Error: No such command "find_or_create_user".`

I configured the FLASK_APP variable as follow:

export FLASK_APP=/mlv/app/commands/cli_commands.py

but got the same error:

When I tried to run the application

`flask run_app --port 5000`

I got this error:

Error: No such command "run_app".

**Comment by Chris1221** [comment]
I'm **not** the developer of the app but have gone through the developer documentation, hopefully the developer will also be able to help. Did you put a leading slash on your FLASK_APP variable on purpose? You may want to ensure that `less $FLASK_APP` or similar actually is able to open the file. Also it should be `--first_name` rather than `--firstname`.

**Comment by fleza** [comment]
Yes, `$FLASK_APP` variable is the path to my  `cli_commands.py` and `less $FLASK_APP` return the script content:

`from app import create_app,db,databases ...`
 I am using `pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)` and `Python 3.8.5 `.
 
What is the `app.zegami.lib`? I have installed all requirements, here is the complete package list:


alabaster                0.7.12     
alembic                  0.9.8      
amqp                     2.3.2      
Babel                    2.6.0      
bcrypt                   3.1.4      
billiard                 3.5.0.4    
blinker                  1.4        
celery                   4.2.0      
certifi                  2018.1.18  
cffi                     1.14.4     
chardet                  3.0.4      
click                    5.1        
cycler                   0.10.0     
decorator                4.3.2      
deepTools                3.3.1      
deeptoolsintervals       0.1.9      
docutils                 0.14       
Flask                    1.0        
Flask-Cors               3.0.7      
Flask-Login              0.4.1      
Flask-Mail               0.9.1      
Flask-Migrate            2.1.1      
Flask-SQLAlchemy         2.3.2      
Flask-User               0.6.19     
Flask-WTF                0.14.2     
freetype-py              2.0.0.post6
idna                     2.6        
imageio                  2.5.0      
imageio-ffmpeg           0.2.0      
imagesize                1.1.0      
itsdangerous             0.24       
Jinja2                   2.10.1     
joblib                   0.14.1     
kiwisolver               1.1.0      
kombu                    4.2.1      
llvmlite                 0.35.0     
Mako                     1.0.7      
MarkupSafe               1.1.1      
matplotlib               3.0.3      
moviepy                  1.0.0      
numba                    0.46.0     
numpy                    1.19.4     
numpydoc                 0.9.1      
packaging                19.0       
passlib                  1.7.1      
Pillow                   7.1.0      
pip                      20.0.2     
pipdeptree               0.13.2     
plotly                   4.3.0      
proglog                  0.1.9      
psycopg2                 2.8.6      
psycopg2-binary          2.8.6      
py2bit                   0.3.0      
pyBigWig                 0.3.16     
pycparser                2.18       
pycryptodome             3.6.6      
pyfaidx                  0.5.6      
Pygments                 2.3.1      
pyparsing                2.3.1      
pysam                    0.16.0     
pytabix                  0.1        
python-dateutil          2.7.0      
python-editor            1.0.3      
python-rapidjson         0.4.3      
pytz                     2018.5     
requests                 2.20.0     
retrying                 1.3.3      
scikit-learn             0.22       
scipy                    1.5.4      
setuptools               45.2.0     
six                      1.11.0     
sklearn                  0.0        
snowballstemmer          1.2.1      
Sphinx                   1.8.3      
sphinx-rtd-theme         0.4.2      
sphinxcontrib-websupport 1.1.0      
SQLAlchemy               1.3.0      
tqdm                     4.31.1     
ujson                    1.35       
umap-learn               0.3.10     
urllib3                  1.24.2     
vine                     1.1.4      
Werkzeug                 0.15.5     
wheel                    0.34.2     
WTForms                  2.1

**Comment by martinSergeant** [comment]
,
Thank you for taking an interest in MLV and sorry for any problems you have
encountered

The app.zegami.lib was a custom package, but lib folders are ignored by the
standard .gitignore so it was not added to the repository, which I have now
done.

Also the cli module has changed so:-
(1) run the app with *flask run *instead of* flask run_app*
(2) Invoke flask commands with a dash instead of an underscore
- flask *find_or_create_user* will now be *flask-find-and-create-user*

I will update this in the help file and please contact me again if there
are any problems

**Comment by fleza** [comment]
Thanks
